name: Build Android App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # هذا الأمر يبحث عن مجلد يحتوي على package.json ويدخل إليه تلقائياً
        run: |
          DIR=$(find . -name "package.json" -exec dirname {} \; | head -n 1)
          cd $DIR
          npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android APK
        run: |
          DIR=$(find . -name "package.json" -exec dirname {} \; | head -n 1)
          cd $DIR
          # مزامنة كاباسيتور مع أندرويد
          npx cap sync android
          cd android
          # بناء ملف APK
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          # يبحث عن ملف الـ APK الناتج في أي مكان
          path: '**/build/outputs/apk/release/*.apk'
